import type { Metadata } from "next";
import { Orbitron } from "next/font/google";
import "./globals.css";

import Header from "./components/header/shared/Header";
import { ThemeProvider } from "./components/theme-provider";
import Navbar from "./components/navbar";

const technoFont = Orbitron({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-techno",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${technoFont.variable} min-h-screen font-sans`}>
        <Header />
        <Navbar />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
